# Generated by Django 3.2.8 on 2021-10-22 15:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('topics', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Topic',
            new_name='Topics',
        ),
    ]
