# Generated by Django 3.2.8 on 2021-10-30 14:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('topics', '0004_topics_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='topics',
            name='details',
            field=models.CharField(default=None, max_length=300),
            preserve_default=False,
        ),
    ]
