# Generated by Django 3.2.9 on 2021-12-05 17:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('topics', '0005_alter_topics_details'),
    ]

    operations = [
        migrations.AlterField(
            model_name='topics',
            name='rating',
            field=models.TextField(),
        ),
    ]
